Repository ubicloud/ubicloud, pull requests merged in 2023-12, with the labels that each got.

#963 Download the ubuntu image from the release instead of daily builds directory
  rhizome/host/lib/vm_setup.rb
  rhizome/host/spec/vm_setup_spec.rb
Labels: bug

#946 Remove extra space at the top of auth page
  clover_web.rb
  views/auth/reset_password_request.erb
  views/layouts/app.erb
Labels: waiting_deployment

#948 Change the account subpages navigator from tab bar to sidebar
  views/account/change_login.erb
  views/account/change_password.erb
  views/account/close_account.erb
  views/account/submenu.erb
  views/account/tab.erb
  views/auth/verify_login_change.erb
Labels: waiting_deployment

#964 Fix available storage decrease issue when a vm allocated on vm host
  prog/vm/nexus.rb
  spec/prog/vm/nexus_spec.rb
Labels: bug, waiting_review

#983 Return empty array as backup list if bucket is not created yet
  model/postgres/postgres_timeline.rb
  spec/model/postgres/postgres_timeline_spec.rb
Labels: waiting_review

#974 Trigger txid_current on parent before starting restore
  model/postgres/postgres_resource.rb
  prog/postgres/postgres_resource_nexus.rb
  spec/prog/postgres/postgres_resource_nexus_spec.rb
Labels: waiting_review

#940 Explicitly set StrictHostKeyChecking
  model/sshable.rb
Labels: waiting_review

#1008 Remove postgres feature flag
  model/project.rb
  routes/web/project/location/postgres.rb
  routes/web/project/postgres.rb
  spec/model/project_spec.rb
  spec/routes/web/project/postgres_spec.rb
  views/layouts/sidebar/content.erb
Labels: waiting_deployment

#1014 Fix cancel links on the resource creating pages
  views/postgres/create.erb
  views/private_subnet/create.erb
  views/vm/create.erb
Labels: bug

#1005 Fix the bug that waiting workflow jobs steal the runners
  routes/web/webhook/github.rb
  spec/routes/web/webhook/github_spec.rb
Labels: bug

#1028 Bump addressable from 2.8.5 to 2.8.6
  Gemfile.lock
Labels: dependencies, ruby

#1009 Adds initial flowtable into nftables definition
  prog/vnet/update_firewall_rules.rb
  spec/prog/vnet/update_firewall_rules_spec.rb
Labels: waiting_review
