Repository ubicloud/ubicloud, pull requests merged in 2024-01, with the labels that each got.

#1038 Load environment variables from /etc/environment to the runner script
  prog/vm/github_runner.rb
  spec/prog/vm/github_runner_spec.rb
Labels: waiting_deployment

#1067 Add a IPv4 flag to vm provisioning API
  routes/api/project/location/vm.rb
  serializers/api/vm.rb
  spec/routes/api/vm_spec.rb
Labels: waiting_review

#1057 Change the runner working directory
  prog/vm/github_runner.rb
Labels: waiting_deployment

#1083 Fix minio_pool vm_size column related migration
  migrate/20231227_add_minio_pool_vm_size.rb
Labels: bug

#1077 Fix the hopped label after refreshing certificate
  prog/postgres/postgres_resource_nexus.rb
  spec/prog/postgres/postgres_resource_nexus_spec.rb
Labels: bug

#1148 Fix nokogiri dependency issue for arm64 alpine image
  Dockerfile
Labels: bug
