Repository ubicloud/ubicloud, pull requests merged in 2024-02, with the labels that each got.

#1143 Change the location for temporary image downloads
  rhizome/host/lib/vm_setup.rb
  rhizome/host/spec/vm_setup_spec.rb
Labels: waiting_deployment

#1171 Improve LearnStorage prog to allow rerunning
  prog/learn_storage.rb
  spec/prog/learn_storage_spec.rb
Labels: bug

#1178 Fix route at verify login change view
  views/auth/verify_login_change.erb
Labels: bug

#1141 Add setup_info file to the runners for display on the GitHub UI
  prog/vm/github_runner.rb
  spec/prog/vm/github_runner_spec.rb
Labels: waiting_deployment

#1194 Add ubi_replication user for PostgreSQL
  model/postgres/postgres_resource.rb
  model/postgres/postgres_server.rb
  prog/postgres/postgres_resource_nexus.rb
  rhizome/postgres/bin/configure
  rhizome/postgres/bin/initialize-empty-database
  spec/model/postgres/postgres_server_spec.rb
Labels: waiting_deployment

#1195 Use /etc/hosts for postgres internal DNS resolving
  model/postgres/postgres_server.rb
  rhizome/postgres/bin/configure
  spec/model/postgres/postgres_server_spec.rb
Labels: waiting_deployment

#1225 Show the email of the current account on the UI
  views/account/change_login.erb
  views/layouts/topbar.erb
Labels: waiting_deployment

#1251 For PG health checks catch exceptions thrown while opening connection
  model/postgres/postgres_server.rb
Labels: waiting_review

#1287 Loosen workflow_job requirement for webhook payloads
  routes/web/webhook/github.rb
  spec/routes/web/webhook/github_spec.rb
Labels: waiting_deployment
